version: '3.4'

services:
  db.local:
    image: postgres
    environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

  frontend:
    image: ${DOCKER_REGISTRY-}frontend
    build:
      context: .
      dockerfile: Frontend/Dockerfile
    depends_on:
      - backend
      - db.local

  backend:
    image: ${DOCKER_REGISTRY-}backend
    build:
      context: .
      dockerfile: Backend/Dockerfile
    depends_on:
      - db.local
    