version: '3.4'

services:

  frontend:
    image: ${DOCKER_REGISTRY-}frontend
    build:
      context: .
      dockerfile: Frontend/Dockerfile
    depends_on:
      - backend
      - postgres

  backend:
    image: ${DOCKER_REGISTRY-}backend
    build:
      context: .
      dockerfile: Backend/Dockerfile
    depends_on:
      - postgres
    ports:
      - "8080:8080"

  postgres:
    image: postgres
    container_name: postgres_container
    environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
        POSTGRES_DB: db
    ports:
      - "5432:5432"
    